import {Config} from '@remotion/cli/config';

// Static assets (captured Playwright footage, narration audio, freeze-frame
// stills) live under video/public/. Captured footage (public/footage/) is
// gitignored and regenerated by `npm run capture`; narration audio and
// stills are committed since they're not cheaply reproducible.
Config.setPublicDir('public');

Config.setVideoImageFormat('jpeg');
Config.setOverwriteOutput(true);
Config.setCodec('h264');
Config.setCrf(28);
Config.setPixelFormat('yuv420p');
